/* Powered by NAIF. Generated by NAIF v.rc2-1.0.0*/
package com.naif.domains.models;

import java.io.Serializable;

import java.util.Date;
import java.util.Set;
import java.util.HashSet;

import java.lang.Override;

import javax.persistence.Table;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Column;
import javax.persistence.JoinColumn;
import javax.persistence.Version;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OrderBy;

import javax.xml.bind.annotation.XmlRootElement;

import com.naif.domains.models.Entities;
import com.naif.domains.models.Entities;
import com.naif.domains.models.Models;
import com.naif.domains.models.NameQueries;
import com.naif.domains.models.LinksModels;
import com.naif.domains.models.Attributes;
import com.naif.domains.models.Relationships;
import com.naif.domains.models.Relationships;

@NamedQueries({
  @NamedQuery(name = "Entities.findAll",
              query = "select o from Entities o"),

  @NamedQuery(name = "Entities.findId",
              query = "select o from Entities o where o.id = :id")
})
@XmlRootElement
@Entity
@Table(name = "entities", catalog="", schema="")

public class Entities implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private Integer optlock;

    private String name;
    private String tabla;
    private String tablaSecuencia;
    private String modifier;
    private String extend;
    private String imports;
    private String annotations;
    private String source;
    private String description;
    private String observaciones;
    private double orden;

    // Uno a Muchos Bidireccional No.5:Entities
    @OneToMany(mappedBy="objPadre",
               fetch=FetchType.LAZY, targetEntity=void.class)
    private Set<Entities> objHijos = new HashSet<Entities>(0);

    // Muchos a Uno Unidireccional No.3:Entities
    @ManyToOne(optional=true,
               fetch=FetchType.LAZY, targetEntity=void.class)
    @JoinColumn(name = "idObjPadre", nullable=true, unique=false,
                insertable=true, updatable=true, columnDefinition="",
                referencedColumnName = "id",table="")
    Entities objPadre;

    // Muchos a Uno Unidireccional No.3:Models
    @ManyToOne(optional=true,
               fetch=FetchType.LAZY, targetEntity=void.class)
    @JoinColumn(name = "idModels", nullable=true, unique=false,
                insertable=true, updatable=true, columnDefinition="",
                referencedColumnName = "id",table="")
    Models models;

    // Uno a Muchos Bidireccional No.5:NameQueries
    @OneToMany(mappedBy="entities",
               fetch=FetchType.LAZY, targetEntity=void.class)
    private Set<NameQueries> nameQueries = new HashSet<NameQueries>(0);

    // Uno a Muchos Bidireccional No.5:LinksModels
    @OneToMany(mappedBy="entities",
               fetch=FetchType.LAZY, targetEntity=void.class)
    private Set<LinksModels> linksModels = new HashSet<LinksModels>(0);

    // Uno a Muchos Bidireccional No.5:Attributes
    @OneToMany(mappedBy="entities",
               fetch=FetchType.LAZY, targetEntity=void.class)
    private Set<Attributes> attributes = new HashSet<Attributes>(0);

    // Uno a Muchos Bidireccional No.5:Relationships
    @OneToMany(mappedBy="from",
               fetch=FetchType.LAZY, targetEntity=void.class)
    private Set<Relationships> from = new HashSet<Relationships>(0);

    // Uno a Muchos Bidireccional No.5:Relationships
    @OneToMany(mappedBy="to",
               fetch=FetchType.LAZY, targetEntity=void.class)
    private Set<Relationships> to = new HashSet<Relationships>(0);



    @Id
    private @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", updatable = false, nullable = false)
    Long id = null;
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Version
    @Column(name = "optlock", nullable=true, unique=false, length=0, precision=0, columnDefinition="")
    public Integer getOptlock() {
        return this.optlock;
    }

    public void setOptlock(Integer optlock) {
        this.optlock = optlock;
    }

    
    @Column(name = "name", nullable=false, unique=false, length=0, precision=0, columnDefinition="")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name = "tabla", nullable=true, unique=false, length=0, precision=0, columnDefinition="")
    public String getTabla() {
        return tabla;
    }

    public void setTabla(String tabla) {
        this.tabla = tabla;
    }

    
    @Column(name = "tablaSecuencia", nullable=true, unique=false, length=0, precision=0, columnDefinition="")
    public String getTablaSecuencia() {
        return tablaSecuencia;
    }

    public void setTablaSecuencia(String tablaSecuencia) {
        this.tablaSecuencia = tablaSecuencia;
    }

    
    @Column(name = "modifier", nullable=true, unique=false, length=0, precision=0, columnDefinition="")
    public String getModifier() {
        return modifier;
    }

    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    
    @Column(name = "extend", nullable=true, unique=false, length=0, precision=0, columnDefinition="")
    public String getExtend() {
        return extend;
    }

    public void setExtend(String extend) {
        this.extend = extend;
    }

    
    @Column(name = "imports", nullable=true, unique=false, length=0, precision=0, columnDefinition="")
    public String getImports() {
        return imports;
    }

    public void setImports(String imports) {
        this.imports = imports;
    }

    
    @Column(name = "annotations", nullable=true, unique=false, length=0, precision=0, columnDefinition="")
    public String getAnnotations() {
        return annotations;
    }

    public void setAnnotations(String annotations) {
        this.annotations = annotations;
    }

    
    @Column(name = "source", nullable=true, unique=false, length=0, precision=0, columnDefinition="")
    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    
    @Column(name = "description", nullable=true, unique=false, length=0, precision=0, columnDefinition="")
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name = "observaciones", nullable=true, unique=false, length=0, precision=0, columnDefinition="")
    public String getObservaciones() {
        return observaciones;
    }

    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    @Column(name = "orden", nullable=true, unique=false, length=0, precision=0, columnDefinition="")
    public double getOrden() {
        return this.orden;
    }

    public void setOrden(double orden) {
        this.orden = orden;
    }

// Relaciones
    // Uno a Muchos Bidireccional No.5:Entities
    public Set<Entities> getObjHijos() {
        return this.objHijos;
    }
    public void setObjHijos(Set<Entities> objHijos) {
        this.objHijos = objHijos;
    }

    // Muchos a Uno Unidireccional No.3:Entities
    public Entities getObjPadre() {
        return this.objPadre;
    }
    public void setObjPadre(Entities objPadre) {
        this.objPadre = objPadre;
    }

    // Muchos a Uno Unidireccional No.3:Models
    public Models getModels() {
        return this.models;
    }
    public void setModels(Models models) {
        this.models = models;
    }

    // Uno a Muchos Bidireccional No.5:NameQueries
    public Set<NameQueries> getNameQueries() {
        return this.nameQueries;
    }
    public void setNameQueries(Set<NameQueries> nameQueries) {
        this.nameQueries = nameQueries;
    }

    // Uno a Muchos Bidireccional No.5:LinksModels
    public Set<LinksModels> getLinksModels() {
        return this.linksModels;
    }
    public void setLinksModels(Set<LinksModels> linksModels) {
        this.linksModels = linksModels;
    }

    // Uno a Muchos Bidireccional No.5:Attributes
    public Set<Attributes> getAttributes() {
        return this.attributes;
    }
    public void setAttributes(Set<Attributes> attributes) {
        this.attributes = attributes;
    }


    @OrderBy("orden ASC")    // Uno a Muchos Bidireccional No.5:Relationships
    public Set<Relationships> getFrom() {
        return this.from;
    }
    public void setFrom(Set<Relationships> from) {
        this.from = from;
    }


    @OrderBy("orden ASC")    // Uno a Muchos Bidireccional No.5:Relationships
    public Set<Relationships> getTo() {
        return this.to;
    }
    public void setTo(Set<Relationships> to) {
        this.to = to;
    }


} // Fin de la clase