/* Powered by NAIF. Generated by NAIF v.rc2-1.0.0*/
package com.naif.domains.models;

import java.io.Serializable;

import java.util.Date;
import java.util.Set;
import java.util.HashSet;

import java.lang.Override;

import javax.persistence.Table;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Column;
import javax.persistence.JoinColumn;
import javax.persistence.Version;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OrderBy;

import javax.xml.bind.annotation.XmlRootElement;

import com.naif.domains.models.Domains;
import com.naif.domains.models.Entities;
import com.naif.domains.models.LinksModels;

@NamedQueries({
  @NamedQuery(name = "Models.findAll",
              query = "select o from Models o"),

  @NamedQuery(name = "Models.findId",
              query = "select o from Models o where o.id = :id")
})
@XmlRootElement
@Entity
@Table(name = "models", catalog="", schema="")

public class Models implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private Integer optlock;

    private String name;
    private String paquete;
    private String codigo;
    private String release;
    private Date date;
    private String description;
    private String observaciones;
    private double orden;

    // Muchos a Uno Unidireccional No.3:Domains
    @ManyToOne(optional=true,
               fetch=FetchType.LAZY, targetEntity=void.class)
    @JoinColumn(name = "idDomains", nullable=true, unique=false,
                insertable=true, updatable=true, columnDefinition="",
                referencedColumnName = "id",table="")
    Domains domains;

    // Uno a Muchos Bidireccional No.5:Entities
    @OneToMany(mappedBy="models",
               fetch=FetchType.LAZY, targetEntity=void.class)
    private Set<Entities> entities = new HashSet<Entities>(0);

    // Uno a Muchos Bidireccional No.5:LinksModels
    @OneToMany(mappedBy="models",
               fetch=FetchType.LAZY, targetEntity=void.class)
    private Set<LinksModels> linksModels = new HashSet<LinksModels>(0);



    @Id
    private @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", updatable = false, nullable = false)
    Long id = null;
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Version
    @Column(name = "optlock", nullable=true, unique=false, length=0, precision=0, columnDefinition="")
    public Integer getOptlock() {
        return this.optlock;
    }

    public void setOptlock(Integer optlock) {
        this.optlock = optlock;
    }

    
    @Column(name = "name", nullable=false, unique=true, length=0, precision=0, columnDefinition="")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name = "paquete", nullable=true, unique=false, length=0, precision=0, columnDefinition="")
    public String getPaquete() {
        return paquete;
    }

    public void setPaquete(String paquete) {
        this.paquete = paquete;
    }

    
    @Column(name = "codigo", nullable=true, unique=false, length=0, precision=0, columnDefinition="")
    public String getCodigo() {
        return codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    
    @Column(name = "release", nullable=true, unique=false, length=0, precision=0, columnDefinition="")
    public String getRelease() {
        return release;
    }

    public void setRelease(String release) {
        this.release = release;
    }

    
    @Column(name = "date", nullable=true, unique=false, length=0, precision=0, columnDefinition="")
    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name = "description", nullable=true, unique=false, length=0, precision=0, columnDefinition="")
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name = "observaciones", nullable=true, unique=false, length=0, precision=0, columnDefinition="")
    public String getObservaciones() {
        return observaciones;
    }

    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    @Column(name = "orden", nullable=true, unique=false, length=0, precision=0, columnDefinition="")
    public double getOrden() {
        return this.orden;
    }

    public void setOrden(double orden) {
        this.orden = orden;
    }

// Relaciones
    // Muchos a Uno Unidireccional No.3:Domains
    public Domains getDomains() {
        return this.domains;
    }
    public void setDomains(Domains domains) {
        this.domains = domains;
    }


    @OrderBy("orden ASC")    // Uno a Muchos Bidireccional No.5:Entities
    public Set<Entities> getEntities() {
        return this.entities;
    }
    public void setEntities(Set<Entities> entities) {
        this.entities = entities;
    }

    // Uno a Muchos Bidireccional No.5:LinksModels
    public Set<LinksModels> getLinksModels() {
        return this.linksModels;
    }
    public void setLinksModels(Set<LinksModels> linksModels) {
        this.linksModels = linksModels;
    }


} // Fin de la clase