/* Powered by NAIF. Generated by NAIF v.rc2-1.0.0*/
package com.naif.domains.models;

import java.io.Serializable;

import java.util.Date;
import java.util.Set;
import java.util.HashSet;

import java.lang.Override;

import javax.persistence.Table;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Column;
import javax.persistence.JoinColumn;
import javax.persistence.Version;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OrderBy;

import org.hibernate.search.annotations.Analyze;
import org.hibernate.search.annotations.DocumentId;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Index;
import org.hibernate.search.annotations.Indexed;
import org.hibernate.search.annotations.Store;

import javax.xml.bind.annotation.XmlRootElement;

import com.naif.domains.models.Domains;
import com.naif.domains.models.LinksModels;

@NamedQueries({
  @NamedQuery(name = "SystemsModels.findAll",
              query = "select o from SystemsModels o"),

  @NamedQuery(name = "SystemsModels.findId",
              query = "select o from SystemsModels o where o.id = :id")
})

@Indexed
@XmlRootElement
@Entity
@Table(name = "systemsModels", catalog="", schema="")

public class SystemsModels implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private Integer optlock;

    @Field(index = Index.YES, analyze = Analyze.NO, store = Store.YES)
    private String name;
    private String observaciones;
    private double orden;

    // Uno a Muchos Bidireccional No.5:Domains
    @OneToMany(mappedBy="systemsModels",
               fetch=FetchType.LAZY, targetEntity=void.class)
    private Set<Domains> domains = new HashSet<Domains>(0);

    // Uno a Muchos Bidireccional No.5:LinksModels
    @OneToMany(mappedBy="systemsModels",
               fetch=FetchType.LAZY, targetEntity=void.class)
    private Set<LinksModels> linksModels = new HashSet<LinksModels>(0);


//    @DocumentId
    @Id
    private @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", updatable = false, nullable = false)
    Long id = null;
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Version
    @Column(name = "optlock", nullable=true, unique=false, length=0, precision=0, columnDefinition="")
    public Integer getOptlock() {
        return this.optlock;
    }

    public void setOptlock(Integer optlock) {
        this.optlock = optlock;
    }


    @Column(name = "name", nullable=false, unique=true, length=0, precision=0, columnDefinition="")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }


    @Column(name = "observaciones", nullable=true, unique=false, length=0, precision=0, columnDefinition="")
    public String getObservaciones() {
        return observaciones;
    }

    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    @Column(name = "orden", nullable=true, unique=false, length=0, precision=0, columnDefinition="")
    public double getOrden() {
        return this.orden;
    }

    public void setOrden(double orden) {
        this.orden = orden;
    }

// Relaciones
    // Uno a Muchos Bidireccional No.5:Domains
    public Set<Domains> getDomains() {
        return this.domains;
    }
    public void setDomains(Set<Domains> domains) {
        this.domains = domains;
    }

    // Uno a Muchos Bidireccional No.5:LinksModels
    public Set<LinksModels> getLinksModels() {
        return this.linksModels;
    }
    public void setLinksModels(Set<LinksModels> linksModels) {
        this.linksModels = linksModels;
    }


} // Fin de la clase