/* Powered by NAIF. Generated by NAIF v.rc2-1.0.0*/
package com.naif.domains.models;

import java.io.Serializable;

import java.util.Date;
import java.util.Set;
import java.util.HashSet;

import java.lang.Override;

import javax.persistence.Table;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Column;
import javax.persistence.JoinColumn;
import javax.persistence.Version;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OrderBy;

import javax.xml.bind.annotation.XmlRootElement;

import com.naif.domains.models.LinksModels;

@NamedQueries({
  @NamedQuery(name = "TiposLinksModels.findAll",
              query = "select o from TiposLinksModels o"),

  @NamedQuery(name = "TiposLinksModels.findId",
              query = "select o from TiposLinksModels o where o.id = :id")
})
@XmlRootElement
@Entity
@Table(name = "tiposLinksModels", catalog="", schema="")

public class TiposLinksModels implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private Integer optlock;

    private String nombre;
    private double orden;

    // Uno a Muchos Bidireccional No.5:LinksModels
    @OneToMany(mappedBy="tiposLinksModels",
               fetch=FetchType.LAZY, targetEntity=void.class)
    private Set<LinksModels> linksModels = new HashSet<LinksModels>(0);



    @Id
    private @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", updatable = false, nullable = false)
    Long id = null;
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Version
    @Column(name = "optlock", nullable=true, unique=false, length=0, precision=0, columnDefinition="")
    public Integer getOptlock() {
        return this.optlock;
    }

    public void setOptlock(Integer optlock) {
        this.optlock = optlock;
    }

    
    @Column(name = "nombre", nullable=false, unique=false, length=0, precision=0, columnDefinition="")
    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "orden", nullable=true, unique=false, length=0, precision=0, columnDefinition="")
    public double getOrden() {
        return this.orden;
    }

    public void setOrden(double orden) {
        this.orden = orden;
    }

// Relaciones
    // Uno a Muchos Bidireccional No.5:LinksModels
    public Set<LinksModels> getLinksModels() {
        return this.linksModels;
    }
    public void setLinksModels(Set<LinksModels> linksModels) {
        this.linksModels = linksModels;
    }


} // Fin de la clase